@startuml

title __APPLICATION's Class Diagram__\n

  namespace com.webcheckers {
    namespace application {
      class com.webcheckers.application.GameCenter {
          {static} - gameIDGenerator : int
          - gamesIDList : HashMap<Integer, Game>
          - gamesList : HashMap<String, Game>
          - opponentList : HashMap<Player, ArrayList<Player>>
          + GameCenter()
          + gameExists()
          + getCorrectKey()
          + getCurrentOpponent()
          + getGame()
          + getGame()
          + getOpponentList()
          + getOpponentStringList()
          + isPlayerInGame()
      }
    }
  }
  

  namespace com.webcheckers {
    namespace application {
      class com.webcheckers.application.PlayerLobby {
          ~ availablePlayerList : HashMap<String, Player>
          ~ requestList : HashMap<Player, LinkedList<Player>>
          {static} - MAX_CHARACTER_LIMIT : int
          {static} - MIN_CHARACTER_LIMIT : int
          + PlayerLobby()
          + getAvailablePlayers()
          + getNumberPlayers()
          + getPlayer()
          + getRequest()
          + hasRequest()
          + sendRequest()
          + signIn()
          + signOut()
          - hasPlayer()
          - nameIsInvalid()
      }
    }
  }
  

  namespace com.webcheckers {
    namespace application {
      enum LoginAttempt {
        INVALID
        NAME_TAKEN
        VALID
      }
    }
  }
  

  com.webcheckers.application.PlayerLobby +-down- com.webcheckers.application.PlayerLobby.LoginAttempt


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
